name: CI

# when this action will run 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#jobs that run sequentially, and also can run in paralles
jobs:
  build:
    #type of runner this job will run on
    runs-on: ubuntu-latest
    # steps are a sequence of tasks , that are part of this job.
    steps:
    # checks out repo under $GITHUB_WORKSPACE, so that your job can access it.
    - uses: actions/checkout@v2
    #run a single command using the runner shell
    - name: Run a 1 line script
      run: echo Hello , this is the FIRST action
    
